# Generated by Django 5.0.3 on 2024-03-18 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "password_confirmation",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("national_id_number", models.CharField(max_length=14, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("blood_type", models.CharField(max_length=5)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pharmacist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "password_confirmation",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=10,
                    ),
                ),
                ("national_id_number", models.CharField(max_length=14, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("age", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "password_confirmation",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("national_id_number", models.CharField(max_length=14, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("membership_no", models.CharField(max_length=30, unique=True)),
                ("graduation_year", models.DateTimeField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("age", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_specialty",
                        to="accounts.specialization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
