# Generated by Django 5.0.3 on 2024-03-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_doctor_graduation_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacist",
            name="status",
            field=models.CharField(default="Pending Approval", max_length=20),
        ),
    ]
