# Generated by Django 5.0.3 on 2024-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_pharmacist_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="status",
            field=models.CharField(default="Pending Approval", max_length=20),
        ),
    ]
