# Generated by Django 5.0.3 on 2024-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_doctor_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="status",
        ),
        migrations.RemoveField(
            model_name="pharmacist",
            name="status",
        ),
        migrations.AddField(
            model_name="doctor",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacist",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
