# Generated by Django 5.0.3 on 2024-03-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_doctor_status_remove_pharmacist_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
            },
        ),
        migrations.AlterModelOptions(
            name="pharmacist",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pharmacist",
                "verbose_name_plural": "Pharmacists",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "Patient_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patients Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
