# Generated by Django 5.0.3 on 2024-03-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_doctorprofile_doctor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="doctor_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to="accounts.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="Patient_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to="accounts.patient",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacistprofile",
            name="pharmacist_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharmacist_profile",
                to="accounts.pharmacist",
            ),
        ),
    ]
